var searchData=
[
  ['relationships',['Relationships',['../classrosette__api_1_1CAPI.html#a74e9f0d663db322cb974733eeb77e0ea',1,'rosette_api.CAPI.Relationships(string content=null, string language=null, string contentType=null, string contentUri=null, string genre=null)'],['../classrosette__api_1_1CAPI.html#a0f9f8675191ef4e48b1a9989989ad32c',1,'rosette_api.CAPI.Relationships(Dictionary&lt; object, object &gt; dict)'],['../classrosette__api_1_1CAPI.html#a5301166c8408313c0c82bdd4c3a6ca9d',1,'rosette_api.CAPI.Relationships(RosetteFile file)']]],
  ['relationshipsresponse',['RelationshipsResponse',['../classrosette__api_1_1RelationshipsResponse.html#a7ac96ce8ab822823334ad0b03ddfa64a',1,'rosette_api.RelationshipsResponse.RelationshipsResponse(HttpResponseMessage apiResult)'],['../classrosette__api_1_1RelationshipsResponse.html#af248775e88efeb3c0c875733a941a585',1,'rosette_api.RelationshipsResponse.RelationshipsResponse(List&lt; RosetteRelationship &gt; relationships, Dictionary&lt; string, string &gt; responseHeaders, Dictionary&lt; string, object &gt; content, string contentAsJson)']]],
  ['removeurlparameter',['RemoveUrlParameter',['../classrosette__api_1_1CAPI.html#a3b25badf80bff4bf9e84d3f35660ac83',1,'rosette_api::CAPI']]],
  ['responseheaders',['ResponseHeaders',['../classrosette__api_1_1ResponseHeaders.html#a1bfcca2b0516bea130265cdd30c8f3a3',1,'rosette_api::ResponseHeaders']]],
  ['rosettecategory',['RosetteCategory',['../classrosette__api_1_1RosetteCategory.html#a834affcd796a68beeba354d0e3f73781',1,'rosette_api::RosetteCategory']]],
  ['rosetteentity',['RosetteEntity',['../classrosette__api_1_1RosetteEntity.html#a5b9d09811b655d491d78499ddd4765bb',1,'rosette_api::RosetteEntity']]],
  ['rosetteexception',['RosetteException',['../classrosette__api_1_1RosetteException.html#a065c5e007dad0541bdfa7cab0400b6b0',1,'rosette_api::RosetteException']]],
  ['rosettefile',['RosetteFile',['../classrosette__api_1_1RosetteFile.html#a8de9c69baf636b615801c57fa3737acc',1,'rosette_api::RosetteFile']]],
  ['rosetterelationship',['RosetteRelationship',['../classrosette__api_1_1RosetteRelationship.html#ab03be216c8ee3f953ede5f02abf5b21e',1,'rosette_api.RosetteRelationship.RosetteRelationship(String predicate, List&lt; String &gt; arguments, List&lt; string &gt; temporals, List&lt; string &gt; locatives, List&lt; string &gt; adjunts, Nullable&lt; decimal &gt; confidence)'],['../classrosette__api_1_1RosetteRelationship.html#a6434cccbe76acc8dd0e538975418cde6',1,'rosette_api.RosetteRelationship.RosetteRelationship(string predicate, Dictionary&lt; int, string &gt; arguments, Dictionary&lt; int, string &gt; IDs, List&lt; string &gt; temporals, List&lt; string &gt; locatives, List&lt; string &gt; adjunts, Nullable&lt; decimal &gt; confidence, HashSet&lt; string &gt; modalities)'],['../classrosette__api_1_1RosetteRelationship.html#abb3b3b4f2a4fe18fdceb7310c4a58070',1,'rosette_api.RosetteRelationship.RosetteRelationship(string predicate, List&lt; Argument &gt; arguments, List&lt; string &gt; temporals, List&lt; string &gt; locatives, List&lt; string &gt; adjunts, Nullable&lt; decimal &gt; confidence, HashSet&lt; string &gt; modalities)']]],
  ['rosetteresponse',['RosetteResponse',['../classrosette__api_1_1RosetteResponse.html#a78162b6a785007f81098792549dabb64',1,'rosette_api.RosetteResponse.RosetteResponse(IDictionary&lt; string, string &gt; headers, IDictionary&lt; string, object &gt; content=null, string contentAsJson=null)'],['../classrosette__api_1_1RosetteResponse.html#ad30f81d4aaf8f0cb77b16bd6eddc6d5b',1,'rosette_api.RosetteResponse.RosetteResponse(HttpResponseMessage responseMsg)']]],
  ['rosettesentiment',['RosetteSentiment',['../classrosette__api_1_1SentimentResponse_1_1RosetteSentiment.html#a1aaec4812d20c0c0419461f1a58f9874',1,'rosette_api.SentimentResponse.RosetteSentiment.RosetteSentiment(String sentiment, Nullable&lt; double &gt; confidence)'],['../classrosette__api_1_1SentimentResponse_1_1RosetteSentiment.html#ad6aa8c2b979f8a44822c323ae981bdf8',1,'rosette_api.SentimentResponse.RosetteSentiment.RosetteSentiment(SentimentLabel sentimentLabel, Nullable&lt; double &gt; confidence)']]],
  ['rosettesentimententity',['RosetteSentimentEntity',['../classrosette__api_1_1RosetteSentimentEntity.html#ac4ec7509f5fe11aec54704f930630091',1,'rosette_api::RosetteSentimentEntity']]]
];
